
version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: work_hours
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DB_HOST: database
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: work_hours
      JWT_SECRET: supersecretkey
      NODE_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
